name: android-apk build

on: [push, pull_request]

jobs:

  make-apk:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pull the Docker Image
      run: docker pull ioanachelaruu/scopy-android:latest
    - name: Run Docker Image
      run: |
            docker run --privileged --net=host \
                -v `pwd`:$GITHUB_WORKSPACE:rw \
                -e "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" \
                -e "BRANCH=${GITHUB_REF#refs/heads/}" \
                ioanachelaruu/scopy-android:latest /bin/bash -xe $GITHUB_WORKSPACE/CI/appveyor/build_scopy_apk.sh
    - uses: actions/upload-artifact@v2
      with:
        name: android-build-debug.apk
        path: ${{ github.workspace }}/android-build-debug.apk
